#!/usr/bin/perl -w

use Cwd;
use File::Spec;
use Getopt::Std qw(getopts);
use strict;
our ($opt_L,$opt_O,$opt_S);
our ($here,$filename,$vol);
our ($bundlelid,$lid);
our ($title,$desc,$docname);
my $obssysfile;

getopts('L:O:S:');
     
if ($opt_L) {
    $bundlelid = $opt_L;
} else {
    die "bundlelid is required";
}
if ($opt_S) {
    $obssysfile = "-S $opt_S";
} else {
    $obssysfile = "";
}

   my $name = $ARGV[0];
   ($vol,$here,$filename) = File::Spec->splitpath($name);
   my @here = File::Spec->splitdir($here);
   while (!($here[0] =~ "document"))  {
           if ($#here < 0) {die "couldn't find document directory in path to make sumpretty label: Need whole path";}
	   shift @here;
   }
# and get rid of the "document" per Bea
   shift @here;
   $lid = join "_", @here;
   $lid .= "$filename";
   $lid = lc $lid;
   $lid =~ s/\.pdf$//;
   $here = File::Spec->catdir(@here);
   $title= "Pretty CW plot for $here";
   $desc="Smoothed and summed spectrum for $here. This plot can be created by summing all of the spectra in this directory and smoothing as stated in the plot.";
   $docname="Smoothed and summed spectrum for $here.";
   `cwplotlabel -e "Nolan, M.C." -T "$title" -d "$desc" -D "$docname" -L $bundlelid -l "$lid" $obssysfile $name`;
