#!/usr/bin/perl -w
use strict;

use Getopt::Std qw(getopts);
our ($opt_h, $opt_t);

getopts("ht:");

my $usage = <<EOT;
Usage: quickpower -t power file.fits [file.fits ...]
    -t:  specify power for each file
    -h:  Print this message.
EOT

if ($opt_h) {
  print STDERR $usage;
  exit;
}

if (not $opt_t) {
  die "-t is required";
}

while (@ARGV) {
  /\D*(\d+)\D*/;
  print "$1 $opt_t\n";
}

